# Generated by Django 4.0 on 2022-03-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Tunis', 'Tunis'), ('Ariana', 'Ariana'), ('Ben arous', 'Ben arous'), ('Mannouba', 'Mannouba'), ('Bizerte', 'Bizerte'), ('Nabeul', 'Nabeul'), ('Béja', 'Béja'), ('Jandouba', 'Jandouba'), ('Zaghouan', 'Zaghouan'), ('Siliana', 'Siliana'), ('Le Kef', 'Le Kef'), ('Sousse', 'Sousse'), ('Monastir', 'Monastir'), ('Mahdia', 'Mahdia'), ('Kasserine', 'Kasserine'), ('Sidi bouzid', 'Sidi bouzid'), ('Kairouan', 'Kairouan'), ('Gafsa', 'Gafsa'), ('sfax', 'sfax'), ('Gabes', 'Gabes'), ('Médenine', 'Médenine'), ('Tozeur', 'Tozeur'), ('Kebili', 'Kebili'), ('Tataouine', 'Tataouine')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.CharField(choices=[('r', 'Residential'), ('c', 'Commercial'), ('i', 'Industrial'), ('l', 'Land'), ('sp', 'Special purpose')], default='', max_length=20)),
                ('surface_area', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('rooms', models.IntegerField(default=0)),
                ('number', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
    ]
